In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import pyro
import pyro.distributions as dist
from pyro.nn import PyroModule, PyroSample
import torch.nn as nn
from pyro.infer import Predictive

###PCA
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

###Forward and Backward Selection
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
import statsmodels.api as sm

# HMC
from pyro.infer import MCMC, NUTS

# variational inference
from pyro.infer import SVI, Trace_ELBO
from pyro.infer.autoguide import AutoDiagonalNormal, AutoMultivariateNormal
from tqdm.auto import trange
from tqdm.notebook import trange

import matplotlib as mpl
import os
import sys
import math

C:\Users\thumo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
### Setting Direction for Optbnn file
sys.path.append(
    r"C:\Users\thumo\OneDrive - Georgia Institute of Technology\Georgia Tech\Semesters\Spring 2025\CSE 8803 IUQ\Project\2-BNN_trained_prior\you-need-a-good-prior"
)

In [3]:
from optbnn.gp.models.gpr import GPR
from optbnn.gp import kernels, mean_functions, priors
from optbnn.bnn.reparam_nets import GaussianMLPReparameterization
from optbnn.bnn.nets.mlp import MLP
from optbnn.bnn.likelihoods import LikGaussian
from optbnn.bnn.priors import FixedGaussianPrior, OptimGaussianPrior
from optbnn.prior_mappers.wasserstein_mapper import MapperWasserstein, WassersteinDistance
from optbnn.utils.rand_generators import MeasureSetGenerator, GridGenerator
from optbnn.utils.normalization import normalize_data
from optbnn.utils.exp_utils import get_input_range
from optbnn.metrics.sampling import compute_rhat_regression
from optbnn.metrics import uncertainty as uncertainty_metrics
from optbnn.sgmcmc_bayes_net.regression_net import RegressionNet
from optbnn.utils import util

In [4]:
###IGNORE THIS IF YOU DON'T HAVE CUDA
import torch

print("CUDA Available:", torch.cuda.is_available())
print("CUDA Device Count:", torch.cuda.device_count())

if torch.cuda.is_available():
    print("CUDA Device Name:", torch.cuda.get_device_name(0))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Training on device: {device}")
print(torch.version.cuda)
print(torch.cuda.device_count())

CUDA Available: False
CUDA Device Count: 0
Training on device: cpu
None
0

In [5]:
class BNN(PyroModule):
    def __init__(self, weight_prior, bias_prior, in_dim=1, out_dim=1, hid_dim=10, n_hid_layers=5):
        '''
        functional model (network architecture):
            a fully connected neural network.

        stochastic model:
            Gaussian prior on weight and bias: p(theta) ~ dist.Normal(0., weight_prior or bias_prior), where weight_prior and bias_prior are learned;
            Gaussian likelihood function: p(y | x, theta) ~ dist.Normal(functional model(x), sigma^2), where sigma ~ dist.Gamma(.5, 1).
        '''
        super().__init__()

        # make sure the dimensions are valid
        assert in_dim > 0 and out_dim > 0 and hid_dim > 0 and n_hid_layers > 0

        # activation function for the whole network, can also be ReLU or LeakyReLU
        self.activation = nn.Tanh()

        # define the layer sizes and the PyroModule layer list
        self.layer_sizes = [in_dim] + n_hid_layers * [hid_dim] + [out_dim]
        layer_list = [PyroModule[nn.Linear](self.layer_sizes[idx - 1], self.layer_sizes[idx]) for idx in
                      range(1, len(self.layer_sizes))]
        self.layers = PyroModule[torch.nn.ModuleList](layer_list)

        # set the probability distribution for each layer's weight and bias
        for layer_idx, layer in enumerate(self.layers):
            layer.weight = PyroSample(dist.Normal(0., weight_prior[layer_idx]).expand([self.layer_sizes[layer_idx + 1], self.layer_sizes[layer_idx]]).to_event(2))
            layer.bias = PyroSample(dist.Normal(0., bias_prior[layer_idx]).expand([self.layer_sizes[layer_idx + 1]]).to_event(1))

    def forward(self, x, y=None):
        # functional model(x)
        # input --> hidden
        x = self.activation(self.layers[0](x))
        # hidden --> hidden
        for layer in self.layers[1:-1]:
            x = self.activation(layer(x))
        # hidden --> output
        mu = self.layers[-1](x).squeeze()

        # sample from P(y | x, \theta)
        sigma = pyro.sample("sigma", dist.Gamma(.5, 1))
        with pyro.plate("data", x.shape[0]):
            # obs is used when quantifying and visualizing the uncertainty of predictions
            obs = pyro.sample("obs", dist.Normal(mu, sigma * sigma), obs=y)
        
        return mu

In [6]:
def plot_predictions(preds, y):
    '''
    Function to visualize the predictions and the uncertainty of predictions.
    '''
    y_pred = preds['obs'].T.detach().numpy().mean(axis=1)
    y_std = preds['obs'].T.detach().numpy().std(axis=1)

    fig, ax = plt.subplots(figsize=(10, 5))

    # decide the range of the y axis based on the number of the labels
    time_idx = np.array(range(len(y)))
    xlims = [time_idx.min() - 0.1, time_idx.max() + 0.1]
    # decide the range of the y axis based on the range of the labels
    ylims = [min(y.min(), y_pred.min()) - 20,
             max(y.max(), y_pred.max()) + 20]
    
    plt.xlim(xlims)
    plt.ylim(ylims)
    plt.xlabel("time", fontsize=20)
    plt.ylabel("closing price", fontsize=20)

    ax.plot(time_idx, y, 'ko', markersize=1, label="observations")
    ax.plot(time_idx, y_pred, '-', linewidth=0.5, color="#408765", label="predictive mean")
    ax.fill_between(time_idx, y_pred - 2 * y_std, y_pred + 2 * y_std, alpha=0.6, color='#86cfac', zorder=0)

    plt.legend(loc=4, fontsize=15, frameon=False)

In [7]:
def plot_uncertainty(preds, y):
    '''
    Function to visualize only the uncertainty.
    '''
    fig, ax = plt.subplots(figsize=(10, 5))

    time_idx = np.array(range(len(y)))
    y_std = preds['obs'].T.detach().numpy().std(axis=1)

    xlims = [time_idx.min() - 0.1, time_idx.max() + 0.1]
    ylims = [y_std.min() - 0.5, y_std.max() + 0.5]

    plt.xlim(xlims)
    plt.ylim(ylims)
    plt.xlabel("time", fontsize=20)
    plt.ylabel("std of closing price", fontsize=20)

    ax.plot(time_idx, y_std, 'ko', markersize=1, label="std of predictions")
    ax.plot(time_idx, y_std, '-', linewidth=0.5, color="#408765")

    plt.legend(loc=4, fontsize=15, frameon=False)

### BNN Prior: Ericcson

In [8]:
df_pre_ericcson = pd.read_csv("pregdprApril2016_Ericcson.csv")
df_pre_ericcson.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,target
0,261755983.0,101.0,10.0,1.0,1.535461,261755983.0,102.8,10.0,1.0,1.535461,...,103.8,10.0,1.0,1.535461,261755983.0,104.8,10.0,1.0,1.535461,103.603225
1,261755983.0,102.8,10.0,1.0,1.535461,261755983.0,103.0,10.0,1.0,1.535461,...,104.8,10.0,1.0,1.535461,261755983.0,106.1,10.0,1.0,1.535461,104.420383
2,261755983.0,103.0,10.0,1.0,1.535461,261755983.0,103.8,10.0,1.0,1.535461,...,106.1,10.0,1.0,1.535461,261755983.0,106.9,10.0,1.0,1.535461,100.434081
3,261755983.0,103.8,10.0,1.0,1.535461,261755983.0,104.8,10.0,1.0,1.535461,...,106.9,10.0,1.0,1.535461,261755983.0,103.5,10.0,1.0,1.585659,99.333622
4,261755983.0,104.8,10.0,1.0,1.535461,261755983.0,106.1,10.0,1.0,1.535461,...,103.5,10.0,1.0,1.585659,261755983.0,102.2,10.0,1.0,1.585659,98.457528

In [9]:
##Extract Values
X_pre_ericcson = df_pre_ericcson.iloc[:, :-1].values
y_pre_ericcson = df_pre_ericcson["target"].values

# Create a mask for rows without NaNs in either X or y
valid_mask = ~np.isnan(X_pre_ericcson).any(axis=1) & ~np.isnan(y_pre_ericcson)

# Apply mask to both X and y
X_pre_ericcson = X_pre_ericcson[valid_mask]
y_pre_ericcson = y_pre_ericcson[valid_mask]
X_pre_ericcson, X_pre_ericcson.shape, type(X_pre_ericcson)

(array([[2.61755983e+08, 1.01000000e+02, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.53546105e+00],
        [2.61755983e+08, 1.02800000e+02, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.53546105e+00],
        [2.61755983e+08, 1.03000000e+02, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.53546105e+00],
        ...,
        [2.61755983e+08, 7.53500000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.66165543e+00],
        [2.61755983e+08, 7.60000000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.66165543e+00],
        [2.61755983e+08, 6.80000000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.66165543e+00]], shape=(264, 25)),
 (264, 25),
 numpy.ndarray)

In [10]:
y_pre_ericcson, y_pre_ericcson.shape, type(y_pre_ericcson)

(array([103.6032248 , 104.42038302, 100.43408099,  99.33362165,
         98.45752819, 100.0186524 , 101.23125207, 101.10614873,
         93.03767666,  92.01955163,  90.96999347,  89.93608061,
         90.25991603,  87.95710513,  87.41993472,  87.75270075,
         86.85316497,  87.9168448 ,  89.76066882,  88.83371273,
         88.29504344,  90.03784912,  90.23791613,  89.99534341,
         88.76077095,  88.62378663,  87.26629422,  86.80584723,
         88.46523094,  87.75840681,  87.89424829,  90.5017429 ,
         89.80511913,  89.71096092,  90.70142546,  89.01046448,
         91.48295834,  91.87129964,  90.25780765,  90.43761205,
         89.6759953 ,  88.69277064,  89.58862255,  87.9351845 ,
         89.01214079,  88.56280145,  87.19603858,  86.23256538,
         87.62017195,  86.0457368 ,  86.28628625,  85.95795004,
         85.29986772,  85.01117751,  86.09688731,  85.43994313,
         85.18051445,  85.62657   ,  85.69985457,  85.65977043,
         85.76486981,  86.67309166,  85.78211323,  84.78073375,
         83.61663163,  84.88319534,  87.78358557,  88.54515521,
         89.58784009,  88.9522888 ,  89.05458921,  89.2866372 ,
         89.8077111 ,  88.14419231,  87.17554612,  87.38127111,
         88.04785612,  87.24107323,  86.35260441,  86.01607465,
         86.23933145,  85.89161382,  87.17120782,  86.63961202,
         86.19219033,  87.79283107,  87.07751388,  87.81625496,
         88.08634479,  86.87826593,  85.99086872,  87.01203649,
         87.26600887,  87.0682717 ,  87.56136063,  88.01884227,
         86.82532569,  83.84753306,  86.54351629,  86.61757495,
         87.13210357,  86.68946101,  86.85730955,  86.61909193,
         86.43854517,  87.61824995,  87.0890848 ,  86.73388542,
         85.16382479,  84.38731105,  85.07214598,  84.25345456,
         83.20915253,  85.2484756 ,  85.11388547,  85.53453535,
         86.09231156,  85.35753563,  85.81654497,  87.35692895,
         86.89190198,  87.34978547,  88.08212954,  88.13611526,
         88.47099256,  89.54539669,  90.16481075,  89.61699994,
         88.60976675,  87.92157396,  90.06367638,  89.38503111,
         88.48772148,  88.79007853,  89.79041392,  89.40331742,
         83.84922191,  83.61981105,  82.94918104,  82.28027254,
         83.18781543,  84.21166988,  83.96440668,  84.87230575,
         86.50717596,  86.06428637,  86.27766718,  88.75689497,
         83.89964494,  83.5327242 ,  82.90465081,  82.19903802,
         86.57815478,  85.17721896,  85.60192711,  84.81242029,
         84.48430042,  85.27451332,  85.23413794,  85.00378911,
         85.45560413,  85.70003951,  86.08499782,  84.73257807,
         86.5031508 ,  88.3306061 ,  86.16495719,  87.35110847,
         86.44493157,  85.4392515 ,  85.0978201 ,  85.56878516,
         85.43459516,  84.37081925,  85.47893636,  85.43401174,
         85.8340193 ,  90.53906934,  89.77397859,  88.97359489,
         88.49273768,  88.29864512,  88.6533348 ,  87.99856566,
         88.39091292,  89.05639015,  90.35735447,  91.20901914,
         90.59318392,  90.96151619,  91.12882003,  88.1262052 ,
         90.41995662,  92.10916841,  90.36945515,  89.91712221,
         93.97111913,  93.86548088,  94.74766934,  90.87452605,
         89.29052562,  87.65837219,  87.94739224,  88.89346187,
         89.18927376,  91.16725562,  91.92279084,  91.45517987,
         92.68245377,  92.83150166,  93.33772171,  92.84750211,
         93.5691249 ,  93.74244036,  93.4865371 ,  94.59694871,
         94.20375726,  94.5617364 ,  94.86834835,  95.22734911,
         95.81571885,  94.02033829,  94.56944739,  94.21291571,
         92.20938509,  93.6917336 ,  92.51185326,  92.78241522,
         93.67772287,  93.27371137,  93.52215639,  92.99344734,
         93.2313802 ,  94.02715912,  94.16351319,  92.87627425,
         94.87032715,  94.98959675,  95.14623521,  95.36191632,
         94.03578433,  95.8111769 ,  97.25731458,  98.38724316,
         99.79980916,  99.68998287,  98.29836121,  98.04826496,
         98.25773802,  99.63156172,  99.5913398 ,  97.38909509,
         97.91464149,  93.44845377,  91.96495119,  90.98213289,
         90.64294227,  91.31109351,  80.66445645,  81.11813922,
         79.94731988,  80.97117966,  80.09571026,  80.41493927]),
 (264,),
 numpy.ndarray)

In [ ]:
%time 
noise_var = 0.1
n_units = 128
n_hidden = 1
activation_fn = "tanh"
num_iters = 300  # Number of iteterations of Wasserstein optimization
lr = 0.05        # The learning rate
n_samples = 128  # The mini-batch size
out_dir = "./exp/gdpr/optim_gaussian"

X_pre_n, y_pre_n, y_mean, y_std = normalize_data(X_pre_ericcson, y_pre_ericcson)
x_min, x_max = get_input_range(X_pre_n, X_pre_n)
epsilon = 1e-6
x_min = np.minimum(x_min, x_max - epsilon)
input_dim, output_dim = int(X_pre_ericcson.shape[-1]), 1
    
# Initialize the measurement set generator
rand_generator = MeasureSetGenerator(X_pre_n, x_min, x_max, 0.7)

# Initialize the mean and covariance function of the target hierarchical GP prior
mean = mean_functions.Zero()
    
lengthscale = math.sqrt(2. * input_dim)
variance = 1.
kernel = kernels.RBF(input_dim=input_dim,
                     lengthscales=torch.tensor([lengthscale], dtype=torch.double),
                     variance=torch.tensor([variance], dtype=torch.double), ARD=True)

# Place hyper-priors on lengthscales and variances
kernel.lengthscales.prior = priors.LogNormal(
    torch.ones([input_dim]) * math.log(lengthscale),
    torch.ones([input_dim]) * 1.)
kernel.variance.prior = priors.LogNormal(
    torch.ones([1]) * 0.1,
    torch.ones([1]) * 1.)
        
# Initialize the GP model
gp = GPR(X=torch.from_numpy(X_pre_n), Y=torch.from_numpy(y_pre_n).reshape([-1, 1]),
             kern=kernel, mean_function=mean)
gp.likelihood.variance.set(noise_var)
    
# Initialize tunable MLP prior
hidden_dims = [n_units] * n_hidden
mlp_reparam = GaussianMLPReparameterization(input_dim, output_dim,
    hidden_dims, activation_fn, scaled_variance=True)
    
mapper = MapperWasserstein(gp, mlp_reparam, rand_generator, out_dir=out_dir,
                               output_dim=output_dim, n_data=100,
                               wasserstein_steps=(0, 300), ###more than 200
                               wasserstein_lr=0.02,
                               logger=None, wasserstein_thres=0.02,
                               n_gpu=1, gpu_gp=True) ##Change GPU if you don't have CUDA; same thing for the post training
    
w_hist = mapper.optimize(num_iters=num_iters, n_samples=n_samples,
                             lr=lr, print_every=10, save_ckpt_every=10, debug=True)

print("----" * 20)

In [ ]:
for name, param in mlp_reparam.named_parameters():
    print(f"parameter name: {name}, parameter shape: {param}")

In [ ]:
def maintain_positivity(x):
    '''
    maintain the positivity of weight and bias standard derivations
    '''
    return np.log(1 + np.exp(x))

pre_weight_prior = [maintain_positivity(4.7054), maintain_positivity(1.1502)]
pre_bias_prior = [maintain_positivity(3.7491), maintain_positivity(-1.8061)]

In [ ]:
def maintain_positivity(x):
    '''
    maintain the positivity of weight and bias standard derivations
    '''
    return np.log(1 + np.exp(x))

pre_weight_prior = [maintain_positivity(4.7054), maintain_positivity(1.1502)]
pre_bias_prior = [maintain_positivity(3.7491), maintain_positivity(-1.8061)]

In [ ]:
%time
num_epochs = 20001 # number of training epoches, 10000 now for quick test: 25000
progress_bar = trange(num_epochs) # show progress bar (only for visualization purpose)

X_pre_n_tensor = torch.tensor(X_pre_n, dtype=torch.float)
y_pre_n_tensor = torch.tensor(y_pre_n, dtype=torch.float)

for epoch in progress_bar:
    loss = svi.step(X_pre_n_tensor, y_pre_n_tensor)
    progress_bar.set_postfix(loss=f"{loss / X_pre_n.shape[0]:.3f}")
    if epoch % 1000 == 0:
        print("[iteration %04d] loss: %.3f" % (epoch + 1, loss / X_pre_n.shape[0])) #14.178

In [ ]:
predictive = Predictive(model_VI, guide=guide, num_samples=1000)

preds = predictive(X_pre_n_tensor)

plot_predictions(preds, y_pre_n_tensor)

In [ ]:
#RMSE
pred_samples = preds["obs"]
pred_mean = pred_samples.mean(dim=0)
# Calculate RMSE
y_true = y_pre_n_tensor
rmse = torch.sqrt(torch.mean((pred_mean - y_true) ** 2))
print(rmse)

In [ ]:
plot_uncertainty(preds, y_pre_n_tensor)

#### Posterior BNN: Ericcsson

In [11]:
df_post_ericcson = pd.read_csv("postgdprMay2018_Ericcson.csv")
df_post_ericcson.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,target
0,261755983.0,63.8,10.0,1.0,1.721164,261755983.0,63.5,10.0,1.0,1.721164,...,62.4,10.0,1.0,1.721164,261755983.0,62.0,10.0,1.0,1.721164,78.598425
1,261755983.0,63.5,10.0,1.0,1.721164,261755983.0,62.7,10.0,1.0,1.721164,...,62.0,10.0,1.0,1.721164,261755983.0,62.3,10.0,1.0,1.721164,81.958706
2,261755983.0,62.7,10.0,1.0,1.721164,261755983.0,62.4,10.0,1.0,1.721164,...,62.3,10.0,1.0,1.721164,261755983.0,63.6,10.0,1.0,1.721164,82.863704
3,261755983.0,62.4,10.0,1.0,1.721164,261755983.0,62.0,10.0,1.0,1.721164,...,63.6,10.0,1.0,1.721164,261755983.0,65.7,10.0,1.0,1.721164,82.616020
4,261755983.0,62.0,10.0,1.0,1.721164,261755983.0,62.3,10.0,1.0,1.721164,...,65.7,10.0,1.0,1.721164,261755983.0,67.1,10.0,1.0,1.721164,83.207702

In [12]:
#Extract Values
X_post_ericcson = df_post_ericcson.iloc[:, :-1].values
y_post_ericcson = df_post_ericcson["target"].values

# Create a mask for rows without NaNs in either X or y
valid_mask = ~np.isnan(X_post_ericcson).any(axis=1) & ~np.isnan(y_post_ericcson)

# Apply mask to both X and y
X_post_ericcson = X_post_ericcson[valid_mask]
y_post_ericcson = y_post_ericcson[valid_mask]
X_post_ericcson, X_post_ericcson.shape, type(X_post_ericcson)

(array([[2.61755983e+08, 6.38000000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.72116375e+00],
        [2.61755983e+08, 6.35000000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.72116375e+00],
        [2.61755983e+08, 6.27000000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.72116375e+00],
        ...,
        [2.61755983e+08, 8.51000000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.74115404e+00],
        [2.61755983e+08, 8.55000000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.74115404e+00],
        [2.61755983e+08, 8.70000000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.74115404e+00]], shape=(389, 25)),
 (389, 25),
 numpy.ndarray)

In [13]:
y_post_ericcson, y_post_ericcson.shape, type(y_post_ericcson)

(array([ 78.59842488,  81.95870643,  82.86370442,  82.61602043,
         83.20770237,  86.1705548 ,  86.93477066,  84.77553639,
         84.53745071,  83.86188259,  84.30710554,  83.30927248,
         85.5364581 ,  84.67808543,  82.75911643,  81.61228306,
         81.90226657,  83.16005061,  82.89991043,  83.55026543,
         84.09792478,  85.06813587,  85.42516464,  83.94829104,
         84.12592007,  90.48415245,  91.15079534,  89.45393926,
         89.52157927,  89.23152271,  89.67287798,  87.17776196,
         86.03570498,  85.45388775,  84.1862738 ,  85.89494583,
         87.5031066 ,  86.10491824,  86.06956188,  86.84555184,
         87.68516836,  87.83171246,  87.63198959,  87.93022772,
         88.19735189,  88.46882608,  89.45382941,  89.15991533,
         90.50718405,  91.90097156,  92.13930397,  94.8089543 ,
         97.4819094 ,  97.65988795,  98.25783065,  98.12220925,
         96.22196082,  96.51852965,  97.86566536,  98.00929751,
         96.68044983, 100.5472203 ,  99.96078357,  99.10752169,
        100.33721968,  99.16161635, 100.20550531, 100.38776403,
         98.72944955,  99.13588292,  99.29233413,  97.89829631,
         99.05018936, 101.34971333, 102.58243528, 101.00824953,
        100.82964373, 100.85544237, 101.27835084, 100.49585937,
        101.50419701, 101.40713543,  99.85586931, 100.00507915,
        101.69067587,  99.80861926,  97.28036261,  95.68022045,
         97.43607387,  99.53441829, 101.62964292, 108.22537785,
        110.10101324, 109.13946347, 106.79083773, 107.51863202,
        104.71352851, 104.7089288 , 105.40538801, 105.8998141 ,
        105.45215378, 105.90943224, 106.58701708, 107.53169004,
        106.82982806, 106.52359309, 106.57967625, 106.1689109 ,
        105.53758684, 104.31884209, 101.69146583, 100.29138567,
        101.91647374, 100.56137248,  98.15289239,  98.23973172,
         97.38680166, 100.43896025, 100.05938611,  99.07009385,
        100.40075756,  98.98310064, 100.43399159, 102.29867254,
        100.6904989 , 100.17799702, 105.02586365, 107.58717177,
        109.00677242, 108.64648851, 110.28788185, 110.33214516,
        109.97415252, 110.23714973, 109.7704981 , 109.35329821,
        108.30146017, 107.95172142, 105.66045843, 107.07647742,
        106.86376271, 104.25121052, 104.63583938, 107.06642243,
        107.95327732, 111.46049197, 106.38457866, 103.64689903,
        102.41206018, 102.79916555, 102.29593467, 101.94968086,
        102.9269469 , 102.08857155, 102.22214392, 102.67275229,
        105.79660274, 108.86941775, 106.46812743, 107.62001706,
        107.81272835, 108.26520099, 107.383343  , 106.25530653,
        104.8784634 , 106.65881658, 105.71041911, 107.89630546,
        108.82809743, 109.7610638 , 112.6032812 , 112.4865739 ,
        111.45990857, 110.60529703, 109.45991904, 109.31750577,
        110.79936743, 113.013474  , 112.39406596, 113.2411088 ,
        110.94599071, 111.19517613, 111.25257459, 111.74300498,
        110.37448918, 109.2461046 , 109.67502619, 112.2305188 ,
        112.2416818 , 111.97697439, 111.28400245, 111.44827351,
        111.94863844, 110.55130381, 114.37296795, 114.25313644,
        115.08287838, 111.33937514, 113.22883021, 112.4133996 ,
        109.76114243, 108.68921071, 108.85984222, 108.98943313,
        110.70729943, 112.57952611, 111.5466268 , 111.61701705,
        112.2955919 , 113.59772167, 114.096307  , 114.15064912,
        115.20371929, 114.75544163, 113.804656  , 119.42139431,
        119.56588967, 118.61999905, 119.02060846, 117.97193445,
        118.48312653, 118.41312425, 116.41562118, 114.87934855,
        113.80453208, 113.26823824, 111.89227468, 112.90244629,
        111.9647281 , 112.11797242, 111.11842565, 111.2611273 ,
        111.69125889, 113.00590393, 113.51677586, 116.57600186,
        118.11049125, 121.67200628, 119.25209812, 120.66081564,
        120.46261973, 121.16276477, 117.06031103, 117.48520354,
        116.8348705 , 117.50192646, 116.38137018, 118.90480016,
        115.91492754, 115.86382236, 115.98422451, 115.28474792,
        113.22592721, 114.96052778, 113.56834462, 115.56046483,
        115.70996061, 113.82355031, 112.50632908, 111.65605118,
        111.01324567, 109.52322088, 109.2715484 , 108.94058025,
        111.27533032, 111.37127183, 112.17863873, 112.33867013,
        113.14866123, 112.89223603, 113.53184092, 114.09643258,
        115.01526499, 113.43664294, 103.82216109, 106.50707954,
        108.77807833, 107.91172409, 108.0932814 , 106.6469238 ,
        109.09731261, 108.34505276, 108.58880013, 109.36160257,
        109.55448033, 111.38295406, 109.46336749, 109.10713788,
        107.82878053, 108.81749142, 110.02805694, 109.83191159,
        109.159634  , 109.39216927, 106.61147351, 105.74448293,
        105.42534567, 106.72908867, 105.69317261, 103.86836442,
        101.83537656, 102.87622169, 101.93406351, 100.87095312,
         97.66366455,  99.95369008,  98.53193979,  97.57407482,
         96.98885228,  96.00882346,  96.81743904,  96.80050784,
         96.28085311,  97.45622719,  96.74480091,  97.12297467,
         96.76519743,  96.38935687,  97.63562245,  99.73899074,
         99.4994919 , 101.17162217,  99.25998517, 100.79132317,
        100.01826842,  96.73199809,  98.04515031,  97.21008944,
         97.57950461,  97.53049505,  97.95576712,  97.26491548,
        100.50403418, 102.51093422, 104.39944911, 103.56218302,
        102.97967004, 102.32087289, 103.53769541, 104.17337965,
        110.34732766, 110.52041523, 108.93659239, 107.91039997,
        109.16133729, 106.71392735, 106.1649586 , 105.76553903,
        103.25740123, 103.28927189, 103.76946121, 103.20636527,
        105.68596595, 103.58308536, 103.36536606, 102.40725474,
        105.03284919, 105.91380103, 105.91514792, 105.40486956,
        105.03165187, 106.68631056, 105.90136056, 106.82907196,
        106.30676513, 107.20467913, 104.97780864, 105.91308204,
        105.33719604, 104.91429841, 105.18434907, 104.32534552,
        105.37984045, 108.37368659, 107.52466225, 107.43329279,
        106.23253546, 106.38249521, 105.13029061, 104.70582492,
        104.76220004, 103.35705268, 104.67464778, 105.73937581,
        104.61500922, 101.56318829, 101.6922533 , 102.73303401,
        103.92627342]),
 (389,),
 numpy.ndarray)

In [ ]:
noise_var = 0.1
n_units = 128
n_hidden = 1
activation_fn = "tanh"
num_iters = 300  # Number of iteterations of Wasserstein optimization
lr = 0.05        # The learning rate
n_samples = 128  # The mini-batch size
out_dir = "./exp/gdpr/optim_gaussian"

X_post_n, y_post_n, y_mean, y_std = normalize_data(X_post_ericcson, y_post_ericcson)
x_min, x_max = get_input_range(X_post_n, X_post_n)
epsilon = 1e-6
x_min = np.minimum(x_min, x_max - epsilon)
input_dim, output_dim = int(X_post_ericcson.shape[-1]), 1
    
# Initialize the measurement set generator
rand_generator = MeasureSetGenerator(X_post_n, x_min, x_max, 0.7)
    
# Initialize the mean and covariance function of the target hierarchical GP prior
mean = mean_functions.Zero()
    
lengthscale = math.sqrt(2. * input_dim)
variance = 1.
kernel = kernels.RBF(input_dim=input_dim,
                     lengthscales=torch.tensor([lengthscale], dtype=torch.double),
                     variance=torch.tensor([variance], dtype=torch.double), ARD=True)

# Place hyper-priors on lengthscales and variances
kernel.lengthscales.prior = priors.LogNormal(
    torch.ones([input_dim]) * math.log(lengthscale),
    torch.ones([input_dim]) * 1.)
kernel.variance.prior = priors.LogNormal(
    torch.ones([1]) * 0.1,
    torch.ones([1]) * 1.)
        
# Initialize the GP model
gp = GPR(X=torch.from_numpy(X_post_n), Y=torch.from_numpy(y_post_n).reshape([-1, 1]),
             kern=kernel, mean_function=mean)
gp.likelihood.variance.set(noise_var)
    
# Initialize tunable MLP prior
hidden_dims = [n_units] * n_hidden
mlp_reparam = GaussianMLPReparameterization(input_dim, output_dim,
    hidden_dims, activation_fn, scaled_variance=True)
    
mapper = MapperWasserstein(gp, mlp_reparam, rand_generator, out_dir=out_dir,
                               output_dim=output_dim, n_data=100,
                               wasserstein_steps=(0, 300), ##Should be more than 200
                               wasserstein_lr=0.02,
                               logger=None, wasserstein_thres=0.1,
                               n_gpu=1, gpu_gp=True) ##Change GPU if you don't have CUDA; same thing for the PRE training
    
w_hist = mapper.optimize(num_iters=num_iters, n_samples=n_samples,
                             lr=lr, print_every=10, save_ckpt_every=10, debug=True)

print("----" * 20)

In [ ]:
for name, param in mlp_reparam.named_parameters():
    print(f"parameter name: {name}, parameter shape: {param}")

In [ ]:
def maintain_positivity(x):
    '''
    maintain the positivity of weight and bias standard derivations
    '''
    return np.log(1 + np.exp(x))

post_weight_prior = [maintain_positivity(2.8332), maintain_positivity(1.0969)]
post_bias_prior = [maintain_positivity(2.0003), maintain_positivity(-0.1846)]

In [ ]:
# clear parameters to ensure every training start from scratch
pyro.clear_param_store()

# set up BNN
model_VI = BNN(post_weight_prior, post_bias_prior, in_dim=25, out_dim=1, hid_dim=128, n_hid_layers=1)

#mean_field_guide = AutoDiagonalNormal(model_VI) # mean field variational inference
guide = AutoMultivariateNormal(model_VI) # use multivariate normal with full covariance to approxiamte posterior

# apply SGD to maximizing the ELBO
optimizer = pyro.optim.Adam({"lr": 0.001})
svi = SVI(model_VI, guide, optimizer, loss=Trace_ELBO())

# # clear parameters to avoid influencing others
pyro.clear_param_store()

In [ ]:
num_epochs = 20001 # number of training epoches, 10000 now for quick test
progress_bar = trange(num_epochs) # show progress bar (only for visualization purpose)

X_post_n_tensor = torch.tensor(X_post_n, dtype=torch.float)
y_post_n_tensor = torch.tensor(y_post_n, dtype=torch.float)

for epoch in progress_bar:
    loss = svi.step(X_post_n_tensor, y_post_n_tensor)
    progress_bar.set_postfix(loss=f"{loss / X_post_n.shape[0]:.3f}")
    if epoch % 1000 == 0:
        print("[iteration %04d] loss: %.3f" % (epoch + 1, loss / X_post_n.shape[0])) ##10.158

In [ ]:
predictive = Predictive(model_VI, guide=guide, num_samples=1000)
preds = predictive(X_post_n_tensor)
plot_predictions(preds, y_post_n_tensor)

In [ ]:
#RMSE
pred_samples = preds["obs"]
pred_mean = pred_samples.mean(dim=0)
# Calculate RMSE
y_true = y_post_n_tensor
rmse = torch.sqrt(torch.mean((pred_mean - y_true) ** 2))
print(rmse)

In [ ]:
plot_uncertainty(preds, y_post_n_tensor)