In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import pyro
import pyro.distributions as dist
from pyro.nn import PyroModule, PyroSample
import torch.nn as nn
from pyro.infer import Predictive

###PCA
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

###Forward and Backward Selection
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
import statsmodels.api as sm

# HMC
from pyro.infer import MCMC, NUTS

# variational inference
from pyro.infer import SVI, Trace_ELBO
from pyro.infer.autoguide import AutoDiagonalNormal, AutoMultivariateNormal
from tqdm.auto import trange
from tqdm.notebook import trange

import matplotlib as mpl
import os
import sys
import math

C:\Users\thumo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [6]:
### Setting Direction for Optbnn file
sys.path.append(
    r"C:\Users\thumo\OneDrive - Georgia Institute of Technology\Georgia Tech\Semesters\Spring 2025\CSE 8803 IUQ\Project\2-BNN_trained_prior\you-need-a-good-prior"
)

In [4]:
from optbnn.gp.models.gpr import GPR
from optbnn.gp import kernels, mean_functions, priors
from optbnn.bnn.reparam_nets import GaussianMLPReparameterization
from optbnn.bnn.nets.mlp import MLP
from optbnn.bnn.likelihoods import LikGaussian
from optbnn.bnn.priors import FixedGaussianPrior, OptimGaussianPrior
from optbnn.prior_mappers.wasserstein_mapper import MapperWasserstein, WassersteinDistance
from optbnn.utils.rand_generators import MeasureSetGenerator, GridGenerator
from optbnn.utils.normalization import normalize_data
from optbnn.utils.exp_utils import get_input_range
from optbnn.metrics.sampling import compute_rhat_regression
from optbnn.metrics import uncertainty as uncertainty_metrics
from optbnn.sgmcmc_bayes_net.regression_net import RegressionNet
from optbnn.utils import util

In [ ]:
###IGNORE THIS IF YOU DON'T HAVE CUDA
import torch

print("CUDA Available:", torch.cuda.is_available())
print("CUDA Device Count:", torch.cuda.device_count())

if torch.cuda.is_available():
    print("CUDA Device Name:", torch.cuda.get_device_name(0))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Training on device: {device}")
print(torch.version.cuda)
print(torch.cuda.device_count())

In [ ]:
class BNN(PyroModule):
    def __init__(self, weight_prior, bias_prior, in_dim=1, out_dim=1, hid_dim=10, n_hid_layers=5):
        '''
        functional model (network architecture):
            a fully connected neural network.

        stochastic model:
            Gaussian prior on weight and bias: p(theta) ~ dist.Normal(0., weight_prior or bias_prior), where weight_prior and bias_prior are learned;
            Gaussian likelihood function: p(y | x, theta) ~ dist.Normal(functional model(x), sigma^2), where sigma ~ dist.Gamma(.5, 1).
        '''
        super().__init__()

        # make sure the dimensions are valid
        assert in_dim > 0 and out_dim > 0 and hid_dim > 0 and n_hid_layers > 0

        # activation function for the whole network, can also be ReLU or LeakyReLU
        self.activation = nn.Tanh()

        # define the layer sizes and the PyroModule layer list
        self.layer_sizes = [in_dim] + n_hid_layers * [hid_dim] + [out_dim]
        layer_list = [PyroModule[nn.Linear](self.layer_sizes[idx - 1], self.layer_sizes[idx]) for idx in
                      range(1, len(self.layer_sizes))]
        self.layers = PyroModule[torch.nn.ModuleList](layer_list)

        # set the probability distribution for each layer's weight and bias
        for layer_idx, layer in enumerate(self.layers):
            layer.weight = PyroSample(dist.Normal(0., weight_prior[layer_idx]).expand([self.layer_sizes[layer_idx + 1], self.layer_sizes[layer_idx]]).to_event(2))
            layer.bias = PyroSample(dist.Normal(0., bias_prior[layer_idx]).expand([self.layer_sizes[layer_idx + 1]]).to_event(1))

    def forward(self, x, y=None):
        # functional model(x)
        # input --> hidden
        x = self.activation(self.layers[0](x))
        # hidden --> hidden
        for layer in self.layers[1:-1]:
            x = self.activation(layer(x))
        # hidden --> output
        mu = self.layers[-1](x).squeeze()

        # sample from P(y | x, \theta)
        sigma = pyro.sample("sigma", dist.Gamma(.5, 1))
        with pyro.plate("data", x.shape[0]):
            # obs is used when quantifying and visualizing the uncertainty of predictions
            obs = pyro.sample("obs", dist.Normal(mu, sigma * sigma), obs=y)
        
        return mu

In [ ]:
def plot_predictions(preds, y):
    '''
    Function to visualize the predictions and the uncertainty of predictions.
    '''
    y_pred = preds['obs'].T.detach().numpy().mean(axis=1)
    y_std = preds['obs'].T.detach().numpy().std(axis=1)

    fig, ax = plt.subplots(figsize=(10, 5))

    # decide the range of the y axis based on the number of the labels
    time_idx = np.array(range(len(y)))
    xlims = [time_idx.min() - 0.1, time_idx.max() + 0.1]
    # decide the range of the y axis based on the range of the labels
    ylims = [min(y.min(), y_pred.min()) - 20,
             max(y.max(), y_pred.max()) + 20]
    
    plt.xlim(xlims)
    plt.ylim(ylims)
    plt.xlabel("time", fontsize=20)
    plt.ylabel("closing price", fontsize=20)

    ax.plot(time_idx, y, 'ko', markersize=1, label="observations")
    ax.plot(time_idx, y_pred, '-', linewidth=0.5, color="#408765", label="predictive mean")
    ax.fill_between(time_idx, y_pred - 2 * y_std, y_pred + 2 * y_std, alpha=0.6, color='#86cfac', zorder=0)

    plt.legend(loc=4, fontsize=15, frameon=False)

In [ ]:
def plot_uncertainty(preds, y):
    '''
    Function to visualize only the uncertainty.
    '''
    fig, ax = plt.subplots(figsize=(10, 5))

    time_idx = np.array(range(len(y)))
    y_std = preds['obs'].T.detach().numpy().std(axis=1)

    xlims = [time_idx.min() - 0.1, time_idx.max() + 0.1]
    ylims = [y_std.min() - 0.5, y_std.max() + 0.5]

    plt.xlim(xlims)
    plt.ylim(ylims)
    plt.xlabel("time", fontsize=20)
    plt.ylabel("std of closing price", fontsize=20)

    ax.plot(time_idx, y_std, 'ko', markersize=1, label="std of predictions")
    ax.plot(time_idx, y_std, '-', linewidth=0.5, color="#408765")

    plt.legend(loc=4, fontsize=15, frameon=False)

#### BNN Prior: Dassault

In [5]:
df_pre_dassault = pd.read_csv("pregdprApril2016_Dassault.csv")
df_pre_dassault.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,target
0,255723498.0,61.03,10.0,1.0,1.163192,255723498.0,61.73,10.0,1.0,1.163192,...,61.83,10.0,1.0,1.163192,255230678.0,63.35,10.0,1.0,1.163192,61.538524
1,255723498.0,61.73,10.0,1.0,1.163192,255230678.0,62.01,10.0,1.0,1.163192,...,63.35,10.0,1.0,1.163192,255230678.0,63.41,10.0,1.0,1.163192,61.742955
2,255230678.0,62.01,10.0,1.0,1.163192,255230678.0,61.83,10.0,1.0,1.163192,...,63.41,10.0,1.0,1.163192,255230678.0,63.52,10.0,1.0,1.163192,60.854215
3,255230678.0,61.83,10.0,1.0,1.163192,255230678.0,63.35,10.0,1.0,1.163192,...,63.52,10.0,1.0,1.163192,255230678.0,63.30,10.0,1.0,1.163192,60.614367
4,255230678.0,63.35,10.0,1.0,1.163192,255230678.0,63.41,10.0,1.0,1.163192,...,63.30,10.0,1.0,1.163192,255230678.0,62.60,10.0,1.0,1.163192,60.945144

In [7]:
# Get both X and y from the DataFrame
X_pre_dassault = df_pre_dassault.iloc[:, :-1].values
y_pre_dassault = df_pre_dassault["target"].values

# Combine them into a single mask
valid_mask = ~np.isnan(X_pre_dassault).any(axis=1) & ~np.isnan(y_pre_dassault)

# Apply the same mask to both
X_pre_dassault = X_pre_dassault[valid_mask]
y_pre_dassault = y_pre_dassault[valid_mask]

In [8]:
X_pre_dassault, X_pre_dassault.shape, type(X_pre_dassault)

(array([[2.55723498e+08, 6.10300000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.16319246e+00],
        [2.55723498e+08, 6.17300000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.16319246e+00],
        [2.55230678e+08, 6.20100000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.16319246e+00],
        ...,
        [2.56725586e+08, 7.12700000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.17027004e+00],
        [2.56725586e+08, 7.13200000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.17027004e+00],
        [2.56725586e+08, 6.83100000e+01, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.17027004e+00]], shape=(269, 25)),
 (269, 25),
 numpy.ndarray)

In [9]:
y_pre_dassault, y_pre_dassault.shape, type(y_pre_dassault)

(array([61.53852442, 61.74295455, 60.8542151 , 60.61436726, 60.94514366,
        61.81897233, 64.62556665, 63.45225425, 66.8413532 , 66.9398132 ,
        68.05238175, 67.13263511, 66.51696291, 67.9197906 , 68.07606449,
        67.77384055, 67.30559209, 67.88407435, 67.37072308, 67.32655019,
        67.93183664, 67.84217944, 68.66282227, 68.34494517, 68.606806  ,
        68.87252653, 69.12276188, 69.27283807, 69.08648979, 68.7138416 ,
        69.37603734, 68.81131577, 68.87932557, 69.13480156, 69.22946182,
        69.69996498, 69.16447566, 69.02814149, 68.39400449, 67.6724961 ,
        68.30552903, 67.17130905, 67.42639018, 67.41212699, 66.77483212,
        67.16903547, 66.46530755, 66.06312233, 66.38106891, 65.9123806 ,
        65.69417283, 65.74160245, 66.44031723, 65.64432867, 65.10969189,
        64.85548837, 65.68128745, 64.79463496, 65.07602665, 65.50459542,
        64.88634277, 64.17099819, 64.46536637, 65.00492282, 64.91808325,
        64.14803501, 64.66642966, 63.92473042, 63.62496784, 65.4328451 ,
        65.34285804, 66.26662933, 66.27793693, 67.94848905, 66.91555678,
        66.15756839, 65.38919338, 65.18560237, 64.89675917, 65.36364106,
        65.58408968, 64.85125355, 64.52609255, 64.09980209, 64.59084969,
        64.86198991, 64.24471017, 64.58235226, 64.99653014, 64.46296301,
        64.62083922, 64.83713317, 64.05397512, 64.21930588, 64.35083751,
        64.79798089, 63.96082145, 62.57406246, 62.58805203, 62.40705473,
        62.92703092, 62.15699228, 61.94999356, 61.76043698, 62.15208301,
        62.16431846, 62.41273886, 63.26759032, 63.41772354, 63.62432961,
        64.21481804, 63.42997274, 64.03374404, 64.87513271, 65.0592514 ,
        66.55904725, 66.38277318, 67.01128749, 68.04527726, 68.41461199,
        67.46634401, 67.93576124, 68.13793021, 68.30935651, 68.02758875,
        68.0630173 , 66.63137508, 66.5550472 , 65.7499531 , 66.10649672,
        67.22022168, 67.40377   , 68.85552988, 68.45191094, 68.31970356,
        68.88267917, 69.11615657, 66.5282386 , 66.61001665, 66.1834044 ,
        66.37793929, 66.58376159, 68.49396727, 68.3110649 , 68.21059888,
        68.64080671, 68.35324896, 69.56507937, 69.13540056, 69.08494142,
        68.29272214, 68.89826336, 69.7742082 , 69.99378237, 69.13047096,
        69.13111947, 68.76684474, 69.05492298, 68.94791406, 69.39357681,
        68.77095536, 68.99544587, 69.00904505, 69.16979792, 69.30480936,
        70.09538596, 70.09848128, 70.8174847 , 71.21965558, 71.93170127,
        71.90867599, 71.01608559, 70.35938582, 71.07490985, 71.34595967,
        71.82380508, 71.60944146, 71.59591288, 70.41794357, 70.7536542 ,
        70.25888265, 69.9981315 , 69.71252709, 69.8539414 , 69.67368131,
        70.01412813, 70.08637166, 69.24173886, 68.81699888, 68.65785873,
        69.47972485, 69.61643938, 69.14764523, 70.14966023, 68.52326773,
        67.8492027 , 66.08594509, 66.89474365, 67.74931961, 68.54748642,
        68.59702464, 68.39856998, 70.65128061, 69.55589831, 70.04931604,
        69.53670066, 70.35650144, 70.46565108, 70.58481614, 71.29811969,
        70.29654326, 68.96791176, 67.92002251, 70.00338398, 70.31482472,
        69.9547801 , 69.51324963, 70.24264702, 70.32751131, 70.51139341,
        70.8192806 , 71.57597109, 70.94479114, 71.14678355, 70.41919198,
        70.57935889, 70.04196895, 70.13395408, 71.18265803, 69.01794522,
        67.98230272, 67.31800422, 67.01258245, 66.77847417, 66.99755028,
        68.08303835, 67.53907919, 68.47781286, 69.02353748, 68.99368044,
        68.58787214, 68.4629423 , 68.32163526, 69.02975269, 69.7223718 ,
        68.58508394, 69.19434571, 69.37406385, 69.00778017, 69.33529486,
        70.46232358, 71.14224783, 71.38722378, 70.44073751, 70.02996728,
        69.64235034, 69.03132793, 68.57718445, 68.32431315, 68.13537943,
        68.11180088, 67.86899667, 68.38313498, 65.50861422, 65.83891869,
        66.15122412, 65.97866816, 66.04124685, 65.32688876]),
 (269,),
 numpy.ndarray)

In [ ]:
noise_var = 0.1
n_units = 128
n_hidden = 1
activation_fn = "tanh"
num_iters = 300  # Number of iteterations of Wasserstein optimization
lr = 0.05        # The learning rate
n_samples = 128  # The mini-batch size
out_dir = "./exp/gdpr/optim_gaussian"

X_pre_n, y_pre_n, y_mean, y_std = normalize_data(X_pre_dassault, y_pre_dassault)
x_min, x_max = get_input_range(X_pre_n, y_pre_n)
epsilon = 1e-6
x_min = np.minimum(x_min, x_max - epsilon)
input_dim, output_dim = int(X_pre_dassault.shape[-1]), 1
    
# Initialize the measurement set generator
rand_generator = MeasureSetGenerator(X_pre_n, x_min, x_max, 0.7)

# Initialize the mean and covariance function of the target hierarchical GP prior
mean = mean_functions.Zero()
    
lengthscale = math.sqrt(2. * input_dim)
variance = 1.
kernel = kernels.RBF(input_dim=input_dim,
                     lengthscales=torch.tensor([lengthscale], dtype=torch.double),
                     variance=torch.tensor([variance], dtype=torch.double), ARD=True)

# Place hyper-priors on lengthscales and variances
kernel.lengthscales.prior = priors.LogNormal(
    torch.ones([input_dim]) * math.log(lengthscale),
    torch.ones([input_dim]) * 1.)
kernel.variance.prior = priors.LogNormal(
    torch.ones([1]) * 0.1,
    torch.ones([1]) * 1.)
        
# Initialize the GP model
gp = GPR(X=torch.from_numpy(X_pre_n), Y=torch.from_numpy(y_pre_n).reshape([-1, 1]),
             kern=kernel, mean_function=mean)
gp.likelihood.variance.set(noise_var)
    
# Initialize tunable MLP prior
hidden_dims = [n_units] * n_hidden
mlp_reparam = GaussianMLPReparameterization(input_dim, output_dim,
    hidden_dims, activation_fn, scaled_variance=True)
    
mapper = MapperWasserstein(gp, mlp_reparam, rand_generator, out_dir=out_dir,
                               output_dim=output_dim, n_data=100,
                               wasserstein_steps=(0, 300), ###more than 200
                               wasserstein_lr=0.02,
                               logger=None, wasserstein_thres=0.02,
                               n_gpu=1, gpu_gp=True) ##Change GPU if you don't have CUDA; same thing for the post training
    
w_hist = mapper.optimize(num_iters=num_iters, n_samples=n_samples,
                             lr=lr, print_every=10, save_ckpt_every=10, debug=True)

print("----" * 20)

In [ ]:
for name, param in mlp_reparam.named_parameters():
    print(f"parameter name: {name}, parameter shape: {param}")

In [ ]:
def maintain_positivity(x):
    '''
    maintain the positivity of weight and bias standard derivations
    '''
    return np.log(1 + np.exp(x))

pre_weight_prior = [maintain_positivity(4.3945), maintain_positivity(1.2164)]
pre_bias_prior = [maintain_positivity(3.0868), maintain_positivity(-2.0868)]

In [ ]:
# clear parameters to ensure every training start from scratch
pyro.clear_param_store()

# set up BNN
model_VI = BNN(pre_weight_prior, pre_bias_prior, in_dim=25, out_dim=1, hid_dim=128, n_hid_layers=1)

#mean_field_guide = AutoDiagonalNormal(model_VI) # mean field variational inference
guide = AutoMultivariateNormal(model_VI) # use multivariate normal with full covariance to approxiamte posterior

# apply SGD to maximizing the ELBO
optimizer = pyro.optim.Adam({"lr": 0.001})
svi = SVI(model_VI, guide, optimizer, loss=Trace_ELBO())

# # clear parameters to avoid influencing others
pyro.clear_param_store()

In [ ]:
%time
num_epochs = 10000 # number of training epoches, 10000 now for quick test: 25000
progress_bar = trange(num_epochs) # show progress bar (only for visualization purpose)

X_pre_n_tensor = torch.tensor(X_pre_n, dtype=torch.float)
y_pre_n_tensor = torch.tensor(y_pre_n, dtype=torch.float)

for epoch in progress_bar:
    loss = svi.step(X_pre_n_tensor, y_pre_n_tensor)
    progress_bar.set_postfix(loss=f"{loss / X_pre_n.shape[0]:.3f}")
    if epoch % 1000 == 0: ##change 1000
        print("[iteration %04d] loss: %.3f" % (epoch + 1, loss / X_pre_n.shape[0])) ##36.699

In [ ]:
predictive = Predictive(model_VI, guide=guide, num_samples=1000)
preds = predictive(X_pre_n_tensor)
plot_predictions(preds, y_pre_n_tensor)

In [ ]:
##RMSE
pred_samples = preds["obs"]
pred_mean = pred_samples.mean(dim=0)
# Calculate RMSE
y_true = y_pre_n_tensor
rmse = torch.sqrt(torch.mean((pred_mean - y_true) ** 2))
print(rmse)

In [ ]:
plot_uncertainty(preds, y_pre_n_tensor)

### BNN Posterior: Dassault

In [10]:
df_post_dassault = pd.read_csv("postgdprMay2018_Dassault.csv")
df_post_dassault.head()

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,target
0,260506586.0,120.65,10.0,1.0,1.191664,260506586.0,121.45,10.0,1.0,1.191664,...,120.30,10.0,1.0,1.191664,260506586.0,118.75,10.0,1.0,1.191664,72.463260
1,260506586.0,121.45,10.0,1.0,1.191664,260506586.0,119.85,10.0,1.0,1.191664,...,118.75,10.0,1.0,1.191664,260506586.0,118.95,10.0,1.0,1.191664,72.526236
2,260506586.0,119.85,10.0,1.0,1.191664,260506586.0,120.30,10.0,1.0,1.191664,...,118.95,10.0,1.0,1.191664,260506586.0,118.55,10.0,1.0,1.191664,74.508429
3,260506586.0,120.30,10.0,1.0,1.191664,260506586.0,118.75,10.0,1.0,1.191664,...,118.55,10.0,1.0,1.191664,260506586.0,119.35,10.0,1.0,1.191664,74.502323
4,260506586.0,118.75,10.0,1.0,1.191664,260506586.0,118.95,10.0,1.0,1.191664,...,119.35,10.0,1.0,1.191664,260506586.0,121.85,10.0,1.0,1.191664,75.535832

In [12]:
##Extract Values
X_post_dassault = df_post_dassault.iloc[:, :-1].values
y_post_dassault = df_post_dassault["target"].values

# Create a mask for rows without NaNs in either X or y
valid_mask = ~np.isnan(X_post_dassault).any(axis=1) & ~np.isnan(y_post_dassault)

# Apply mask to both X and y
X_post_dassault = X_post_dassault[valid_mask]
y_post_dassault = y_post_dassault[valid_mask]

In [13]:
X_post_dassault, X_post_dassault.shape, type(X_post_dassault)

(array([[2.60506586e+08, 1.20650000e+02, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.19166443e+00],
        [2.60506586e+08, 1.21450000e+02, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.19166443e+00],
        [2.60506586e+08, 1.19850000e+02, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.19166443e+00],
        ...,
        [2.62927968e+08, 1.43150000e+02, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.19752138e+00],
        [2.62927968e+08, 1.43250000e+02, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.19752138e+00],
        [2.62927968e+08, 1.43850000e+02, 1.00000000e+01, ...,
         1.00000000e+01, 1.00000000e+00, 1.19752138e+00]], shape=(398, 25)),
 (398, 25),
 numpy.ndarray)

In [14]:
y_post_dassault, y_post_dassault.shape, type(y_post_dassault)

(array([72.46326003, 72.5262357 , 74.50842943, 74.50232256, 75.53583187,
        76.57507706, 76.39268269, 76.37525899, 75.25164013, 73.45801233,
        73.73675369, 73.97438282, 74.59845874, 73.82270145, 73.0707952 ,
        72.70803648, 72.66400094, 71.98984022, 72.62764333, 72.74684127,
        72.83976136, 74.35947857, 75.28881848, 76.52861812, 76.49438918,
        77.15176437, 77.89188218, 77.7023347 , 77.50102448, 76.5093257 ,
        75.52173412, 75.24501902, 73.48477162, 75.39237725, 75.40275557,
        74.40197061, 74.17470031, 74.25358222, 75.90373332, 75.019253  ,
        75.0586543 , 73.46307012, 74.46146683, 75.18833002, 75.90962332,
        77.0081488 , 78.44104714, 78.24649973, 78.34005823, 78.1356668 ,
        79.35384873, 78.55931344, 79.02810668, 80.10896386, 80.29243862,
        81.58037554, 80.90179801, 80.80184494, 81.73978026, 82.35795575,
        82.33427182, 80.42635533, 77.66465211, 77.14932824, 77.00010139,
        77.06842568, 76.82347083, 77.1600428 , 76.52123339, 77.61063315,
        77.12695874, 77.93723314, 76.3704661 , 73.78704589, 73.92552798,
        74.36943317, 74.60412124, 74.28210337, 73.71468276, 74.37572   ,
        74.66173802, 74.81750545, 73.9969185 , 73.79335811, 71.53889631,
        69.94589947, 69.94001876, 67.01253968, 67.81218048, 68.456335  ,
        66.84747091, 68.86812045, 68.90788701, 68.79497491, 68.48095081,
        68.21435006, 65.05599775, 66.0895836 , 67.6948978 , 65.76758295,
        63.33562435, 63.3099968 , 65.11073443, 64.1977955 , 64.00157374,
        62.54539241, 62.84504482, 64.34178455, 64.34370668, 64.86164754,
        63.6328366 , 63.33268808, 62.42221975, 63.05680615, 64.01654659,
        62.16737746, 61.22644298, 60.58230382, 60.20356663, 59.79321473,
        59.96309955, 59.90711776, 61.83133154, 62.47086516, 61.53325635,
        64.3804288 , 62.08182171, 62.03843925, 62.86011573, 62.44377218,
        62.48076284, 64.77408288, 65.36492339, 64.52895043, 62.1441193 ,
        61.17704622, 61.14328927, 62.51266852, 60.98376929, 60.49965497,
        60.42835429, 61.77243422, 61.39561696, 62.37531472, 61.8004202 ,
        58.11037844, 59.10018122, 60.56419661, 61.06372105, 62.48303308,
        62.93454367, 62.57104014, 62.30139566, 62.55366913, 62.82305029,
        63.36009836, 64.15053288, 64.1782529 , 63.5614142 , 63.79062405,
        63.84274061, 64.06699644, 62.89088625, 62.92069726, 62.77040239,
        62.29530809, 62.1319581 , 63.34229995, 65.11653576, 71.60759424,
        72.08011703, 71.50385914, 71.53178788, 70.1443216 , 70.79372765,
        70.43017339, 70.28376223, 70.23031742, 69.73970828, 69.95571504,
        69.39065925, 70.22108336, 69.44775324, 69.69213146, 69.01658107,
        69.52135175, 70.04311986, 69.22070809, 70.48083788, 68.45582716,
        69.03875144, 69.68353126, 69.27401614, 69.23349467, 70.00904615,
        69.0101105 , 69.49146385, 67.91237675, 68.14946598, 68.34754151,
        68.34568077, 68.42632434, 68.21507741, 69.38443796, 67.28488022,
        68.31523066, 69.04528108, 68.78916629, 68.51342199, 69.11662767,
        68.15862869, 67.99304873, 68.65971854, 68.37510393, 67.93518985,
        67.95558933, 68.51894132, 68.66899909, 68.33983145, 68.31877998,
        68.79527966, 68.90087942, 71.7601607 , 71.81365335, 70.38110839,
        69.67836386, 70.69324582, 68.79460161, 67.82054915, 68.64732507,
        68.56477094, 69.25135363, 69.63730625, 69.8517231 , 68.6707038 ,
        69.3195357 , 68.4242372 , 69.85275564, 71.28640337, 69.92146392,
        70.51451539, 71.00052012, 69.98335765, 69.39375237, 68.77524428,
        67.81592759, 67.76858423, 67.92398854, 68.27327565, 68.18180936,
        65.86893766, 67.1093805 , 66.67738821, 67.90832604, 67.83406498,
        67.91108722, 67.24632329, 68.54361292, 68.30747683, 68.72773187,
        69.70911206, 69.35579379, 69.48690412, 67.97803404, 68.15416628,
        68.91429124, 68.60350849, 68.36523174, 68.57524554, 69.62060796,
        69.83741364, 70.31062559, 68.8677753 , 67.91720074, 67.56859266,
        67.40571826, 67.46321412, 67.92299272, 67.56329091, 67.46108355,
        66.75577604, 66.71095426, 65.39186822, 65.59340343, 64.93899878,
        64.27058822, 67.39451191, 65.53291688, 66.42646778, 66.12790023,
        65.93116352, 66.3228853 , 66.79043972, 65.83864576, 64.10358717,
        64.03783221, 64.55041522, 64.8681604 , 64.10774562, 63.39704726,
        63.77696382, 62.52380429, 62.0507352 , 62.6785692 , 62.4862636 ,
        62.96783093, 64.12212244, 62.00157167, 62.16609065, 62.50692786,
        62.47243686, 61.28398981, 60.83144022, 61.35491816, 60.84500523,
        61.09069585, 61.28825019, 60.8254822 , 60.87035976, 59.52903625,
        59.14820662, 59.43194474, 60.47731348, 61.1593716 , 60.29059459,
        61.51634811, 61.68339495, 60.26746038, 60.30882146, 58.62037618,
        58.33832693, 58.04505346, 60.38209353, 60.63458066, 59.80721102,
        59.73447741, 60.05515437, 61.15794442, 61.77488821, 61.95994565,
        62.44514286, 62.97727764, 62.77271824, 63.28082405, 63.22914224,
        63.49650352, 63.73059701, 62.90251286, 62.25928694, 61.79412306,
        60.56645759, 60.36556958, 59.52260159, 60.0906968 , 60.91922818,
        60.52818999, 61.11529009, 61.0507079 , 60.59224302, 60.16830577,
        59.9657738 , 60.03322815, 60.22839442, 60.00295474, 61.02328214,
        60.9451282 , 61.29633106, 61.51379141, 61.2804286 , 61.72147813,
        61.10363692, 62.00587132, 61.69532458, 61.27074931, 61.17814183,
        62.18733336, 61.81092812, 61.69261078, 62.01529062, 61.35900319,
        61.73482613, 61.80032512, 61.64006141, 62.9377766 , 63.0625552 ,
        61.91197394, 60.91294448, 60.62687157, 60.68771834, 61.20806715,
        61.29960056, 61.2500849 , 62.15813021, 61.73689168, 62.17808906,
        62.24575013, 61.67201934, 62.20000068]),
 (398,),
 numpy.ndarray)

In [ ]:
noise_var = 0.1
n_units = 128
n_hidden = 1
activation_fn = "tanh"
num_iters = 300  # Number of iteterations of Wasserstein optimization
lr = 0.05        # The learning rate
n_samples = 128  # The mini-batch size
out_dir = "./exp/gdpr/optim_gaussian"

X_post_n, y_post_n, y_mean, y_std = normalize_data(X_post_dassault, y_post_dassault)
x_min, x_max = get_input_range(X_post_n, X_post_n)
epsilon = 1e-6
x_min = np.minimum(x_min, x_max - epsilon)
input_dim, output_dim = int(X_post_dassault.shape[-1]), 1
    
# Initialize the measurement set generator
rand_generator = MeasureSetGenerator(X_post_n, x_min, x_max, 0.7)
    
# Initialize the mean and covariance function of the target hierarchical GP prior
mean = mean_functions.Zero()
    
lengthscale = math.sqrt(2. * input_dim)
variance = 1.
kernel = kernels.RBF(input_dim=input_dim,
                     lengthscales=torch.tensor([lengthscale], dtype=torch.double),
                     variance=torch.tensor([variance], dtype=torch.double), ARD=True)

# Place hyper-priors on lengthscales and variances
kernel.lengthscales.prior = priors.LogNormal(
    torch.ones([input_dim]) * math.log(lengthscale),
    torch.ones([input_dim]) * 1.)
kernel.variance.prior = priors.LogNormal(
    torch.ones([1]) * 0.1,
    torch.ones([1]) * 1.)
        
# Initialize the GP model
gp = GPR(X=torch.from_numpy(X_post_n), Y=torch.from_numpy(y_post_n).reshape([-1, 1]),
             kern=kernel, mean_function=mean)
gp.likelihood.variance.set(noise_var)
    
# Initialize tunable MLP prior
hidden_dims = [n_units] * n_hidden
mlp_reparam = GaussianMLPReparameterization(input_dim, output_dim,
    hidden_dims, activation_fn, scaled_variance=True)
    
mapper = MapperWasserstein(gp, mlp_reparam, rand_generator, out_dir=out_dir,
                               output_dim=output_dim, n_data=100,
                               wasserstein_steps=(0, 300), ##Should be more than 200
                               wasserstein_lr=0.02,
                               logger=None, wasserstein_thres=0.1,
                               n_gpu=1, gpu_gp=True) ##Change GPU if you don't have CUDA; same thing for the PRE training
    
w_hist = mapper.optimize(num_iters=num_iters, n_samples=n_samples,
                             lr=lr, print_every=10, save_ckpt_every=10, debug=True)

print("----" * 20)

In [ ]:
for name, param in mlp_reparam.named_parameters():
    print(f"parameter name: {name}, parameter shape: {param}")

In [ ]:
def maintain_positivity(x):
    '''
    maintain the positivity of weight and bias standard derivations
    '''
    return np.log(1 + np.exp(x))

post_weight_prior = [maintain_positivity(3.3871), maintain_positivity(1.1624)]
post_bias_prior = [maintain_positivity(2.3243), maintain_positivity(-0.4564)]

In [ ]:
# clear parameters to ensure every training start from scratch
pyro.clear_param_store()

# set up BNN
model_VI = BNN(post_weight_prior, post_bias_prior, in_dim=25, out_dim=1, hid_dim=128, n_hid_layers=1)

#mean_field_guide = AutoDiagonalNormal(model_VI) # mean field variational inference
guide = AutoMultivariateNormal(model_VI) # use multivariate normal with full covariance to approxiamte posterior

# apply SGD to maximizing the ELBO
optimizer = pyro.optim.Adam({"lr": 0.001})
svi = SVI(model_VI, guide, optimizer, loss=Trace_ELBO())

# # clear parameters to avoid influencing others
pyro.clear_param_store()

In [ ]:
num_epochs = 20001 # number of training epoches, 10000 now for quick test
progress_bar = trange(num_epochs) # show progress bar (only for visualization purpose)

X_post_n_tensor = torch.tensor(X_post_n, dtype=torch.float)
y_post_n_tensor = torch.tensor(y_post_n, dtype=torch.float)

for epoch in progress_bar:
    loss = svi.step(X_post_n_tensor, y_post_n_tensor)
    progress_bar.set_postfix(loss=f"{loss / X_post_n.shape[0]:.3f}")
    if epoch % 1000 == 0:
        print("[iteration %04d] loss: %.3f" % (epoch + 1, loss / X_post_n.shape[0])) #11.525

In [ ]:
predictive = Predictive(model_VI, guide=guide, num_samples=1000)
preds = predictive(X_post_n_tensor)
plot_predictions(preds, y_post_n_tensor)

In [ ]:
##RMSE
pred_samples = preds["obs"]
pred_mean = pred_samples.mean(dim=0)
# Calculate RMSE
y_true = y_post_n_tensor
rmse = torch.sqrt(torch.mean((pred_mean - y_true) ** 2))
print(rmse)

In [ ]:
plot_uncertainty(preds, y_post_n_tensor)